"""basically complete

Revision ID: efdd2c6ac56f
Revises: a30fdae9bbee
Create Date: 2020-05-26 20:12:33.064278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdd2c6ac56f'
down_revision = 'a30fdae9bbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posttype',
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comment',
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reply_id', sa.Integer(), nullable=True),
    sa.Column('up', sa.Integer(), nullable=True),
    sa.Column('down', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['reply_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('content', sa.String(length=600), nullable=True))
    op.add_column('post', sa.Column('thumbnail_url', sa.String(length=300), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=300), nullable=True))
    op.add_column('post', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'posttype', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'type_id')
    op.drop_column('post', 'title')
    op.drop_column('post', 'thumbnail_url')
    op.drop_column('post', 'content')
    op.drop_table('comment')
    op.drop_table('posttype')
    # ### end Alembic commands ###
