# Generated by Django 2.1.7 on 2020-04-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='online_play_url',
            field=models.URLField(help_text='在线播放URL', null=True, verbose_name='在线播放URL'),
        ),
    ]
